// <auto-generated />

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace MindboxTestApp.Core.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    internal class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10");

            modelBuilder.Entity("MindboxTestApp.Core.Entities.Ellipse", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("Discriminator")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<double>("MajorAxisLength")
                    .HasColumnType("REAL");

                b.Property<double>("MinorAxisLength")
                    .HasColumnType("REAL");

                b.HasKey("Id");

                b.ToTable("Ellipses");

                b.HasDiscriminator<string>("Discriminator").HasValue("Ellipse");
            });

            modelBuilder.Entity("MindboxTestApp.Core.Entities.Triangle", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<double>("ABAngle")
                    .HasColumnType("REAL");

                b.Property<double>("ALength")
                    .HasColumnType("REAL");

                b.Property<double>("BLength")
                    .HasColumnType("REAL");

                b.HasKey("Id");

                b.ToTable("Triangles");
            });

            modelBuilder.Entity("MindboxTestApp.Core.Entities.Circle", b =>
            {
                b.HasBaseType("MindboxTestApp.Core.Entities.Ellipse");

                b.HasDiscriminator().HasValue("Circle");
            });
#pragma warning restore 612, 618
        }
    }
}